package org.ninelym.togai

/**
 * Build configuration constants
 * Generated by Gradle build system
 */
object BuildConfig {
    const val DEBUG = true
    const val APPLICATION_ID = "org.ninelym.togai"
    const val BUILD_TYPE = "debug"
    const val VERSION_CODE = 1
    const val VERSION_NAME = "1.0.0"
}
